services:
  postgres:
    image: postgres:latest
    container_name: tasks_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
